server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pdftocsv-service
          uri: lb://pdftocsv-service
          predicates:
            - Path=/api/v1/mallas/admin/PdfToCsv
        - id: map-service
          uri: lb://map-service
          predicates:
            - Path=/api/v1/asignaturas/admin/**
        - id: createmalla-service
          uri: lb://createmalla-service
          predicates:
            - Path=/api/v1/mallas/admin/crearMalla
        - id: mallalist-service
          uri: lb://mallalist-service
          predicates:
            - Path=/api/v1/mallas/**, /api/v1/mallaToUsuario/**, /api/v1/keycloak/**, /api/v1/mallascsv/**
